apiVersion: v1
kind: ConfigMap
metadata:
  name: dolibarr-config
  namespace: __CUSTOMER_NAMESPACE__
  labels:
    app: dolibarr
    customer: __CUSTOMER_NAME__
data:
  DOLI_DB_HOST: mariadb
  DOLI_DB_NAME: dolibarr
  DOLI_DB_USER: dolibarr
  DOLI_ADMIN_LOGIN: admin
  DOLI_URL_ROOT: "https://__CUSTOMER_DOMAIN__"
  DOLI_MODULES: ""
  PHP_INI_DATE_TIMEZONE: "Africa/Accra"
