apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolibarr-documents
  namespace: __CUSTOMER_NAMESPACE__
  labels:
    app: dolibarr
    customer: __CUSTOMER_NAME__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
